---

name: Continuous Integration

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - "!master"
      - "!staging"

jobs:
  Test:
    runs-on: ubuntu-latest

    container:
      image: elixir:1.11-alpine

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

      rabbitmq:
        image: rabbitmq:3-alpine
        env:
          RABBITMQ_DEFAULT_USER: assembly
          RABBITMQ_DEFAULT_PASS: system76

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install (os)
        run: apk add --no-cache gcc g++ git make musl-dev tar zstd

      - name: Install (mix)
        run: |
          mix local.rebar --force
          mix local.hex --force

      - name: Cache
        uses: actions/cache@v2
        id: cache
        with:
          key: elixir-${{ hashFiles('Dockerfile', 'mix.lock') }}-${{ github.ref }}-test
          restore-keys: |
            elixir-${{ hashFiles('Dockerfile', 'mix.lock') }}-${{ github.ref }}-
            elixir-${{ hashFiles('Dockerfile', 'mix.lock') }}-
            elixir-
          path: |
            _build
            deps

      - name: Install (deps)
        if: steps.cache.outputs.cache-hit != 'true'
        run: mix deps.get

      - name: Run Tests
        run: mix test
        env:
          DB_HOST: postgres
          RABBITMQ_HOST: rabbitmq

  Format:
    runs-on: ubuntu-latest

    container:
      image: elixir:1.11-alpine

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install (os)
        run: apk add --no-cache gcc g++ git make musl-dev

      - name: Install (mix)
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Run Formatter
        run: mix format --check-formatted

  Credo:
    runs-on: ubuntu-latest

    container:
      image: elixir:1.11-alpine

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install (os)
        run: apk add --no-cache gcc g++ git make musl-dev tar zstd

      - name: Install (mix)
        run: |
          mix local.rebar --force
          mix local.hex --force

      - name: Cache
        uses: actions/cache@v2
        id: cache
        with:
          key: elixir-${{ hashFiles('Dockerfile', 'mix.lock') }}-${{ github.ref }}-credo
          restore-keys: |
            elixir-${{ hashFiles('Dockerfile', 'mix.lock') }}-${{ github.ref }}-
            elixir-${{ hashFiles('Dockerfile', 'mix.lock') }}-
            elixir-
          path: |
            _build
            deps

      - name: Install (deps)
        if: steps.cache.outputs.cache-hit != 'true'
        run: mix deps.get

      - name: Run Credo
        run: mix credo

  Dialyzer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: '22.2'
          elixir-version: '1.12.2'

      - name: Cache
        uses: actions/cache@v2
        id: cache
        with:
          key: elixir-${{ hashFiles('Dockerfile', 'mix.lock') }}-${{ github.ref }}-dialyzer
          restore-keys: |
            elixir-${{ hashFiles('Dockerfile', 'mix.lock') }}-${{ github.ref }}-
            elixir-${{ hashFiles('Dockerfile', 'mix.lock') }}-
            elixir-
          path: |
            _build
            deps
            priv/plts

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Run Dialyzer
        run: mix dialyzer
